version: '3.8'
services:
  app:
    container_name: ostoslista
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/usr/src/app/src
      - ./target:/usr/src/app/target
      - ./data:/data
    environment:
      db: ${db}
      user: ${user}
      pass: ${pass}
  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${db}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pass}
    ports:
      - "5432:5432"
volumes:
  postgres_data:
