version: '3.8'
services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres_db
    env_file: ".env"
    environment:
      POSTGRES_DB: ${db}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pass}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    depends_on: 
      - db
    image: juhomarila/ostoslista-app:latest
    container_name: ostoslista
    ports:
      - 8080:8080
    env_file: ".env"
    environment:
      db: ${db}
      user: ${user}
      pass: ${pass}
      secret: ${secret} 
      userEntity: ${userEntity}
      userEntityPass: ${userEntityPass}