version: '3.8'
services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: postgres_db
    env_file: ".env"
    environment:
      POSTGRES_DB: ${db}
      POSTGRES_USER: ${user}
      POSTGRES_PASSWORD: ${pass}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ostoslista
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${user} -d ${db}'"]
      interval: 10s
      timeout: 3s
      retries: 3
  app:
    depends_on: 
      db:
        condition: service_healthy
    image: juhomarila/ostoslista-app:latest
    container_name: ostoslista
    ports:
      - 8080:8080
    env_file: ".env"
    environment:
      db: ${db}
      user: ${user}
      pass: ${pass}
      secret: ${secret} 
      userEntity: ${userEntity}
      userEntityPass: ${userEntityPass}
    networks:
      - ostoslista
  elastic:
    depends_on: 
      db:
        condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - ostoslista
    volumes:
      - ./elastic:/usr/share/elasticsearch/data
networks:
  ostoslista:
    external: true