package fi.ruoka.ostoslista.enums;

public enum Tuotteet {
    LENKKARIT("Lenkkarit", 1),
    LUISTIMET("Luistimet", 1),
    JÄÄKIEKKOTEIPPI("Kiekkoteippi", 1),
    JÄÄKIEKKOKYPÄRÄ("Jääkiekkokypärä", 1),
    PYÖRÄILYKYPÄRÄ("Pyöräilykypärä", 1),
    JALKAPALLO("Jalkapallo", 1),
    PYÖRÄNLUKKO("Pyöränlukko", 1),
    POLKUPYÖRÄ("Polkupyörä", 1),
    LATURI("Laturi", 2),
    NÄYTÖNSUOJA("Näytönsuoja", 2),
    HAMMASHARJANVAIHTOPÄÄ("Hammasharjan vaihtopää", 2),
    SÄHKÖHAMMASHARJA("Sähköhammasharja", 2),
    KENGÄTMIMMI("Kengät Mimmille", 3),
    KENGÄTISI("Kengät Isille", 3),
    TOSSUMIMMI("Sisätossut Mimmille", 3),
    SLÄPÄRITISI("Släpärit Isille", 3),
    SLÄPÄRITMIMMI("Släpärit Mimmille", 3),
    BOKSERITISI("Bokserit Isille", 4),
    PIKKARITMIMMI("Pikkarit Mimmille", 4),
    SUKATISI("Sukat Isille", 4),
    SUKATMIMMI("Sukat Mimmille", 4),
    SUKATÄITI("Sukat Äidille", 4),
    LIPPISMIMMI("Lippis Mimmille", 4),
    PIIRUSTUSPAPERIA("Piirustuspaperia", 5),
    KYNÄ("Kyniä", 5),
    VÄRITYSKIRJA("Värityskirja", 5),
    KIRJA("Kirja", 5),
    ASKARTELUKIRJA("Askartelukirja", 5),
    PALAPELI("Palapeli", 6),
    NUKKE("Nukke", 6),
    AUTO("Auto", 6),
    PALIKAT("Palikat", 6),
    LELUMIMMI("Lelu Mimmille", 6),
    LELULAHJAKSI("Lelu Lahjaksi", 6),
    AA_PARISTO("AA-paristoja", 7),
    AAA_PARISTO("AAA-paristoja", 7),
    LR_44_PARISTO("LR44-paristoja", 7),
    CR2032_PARISTO("CR2032-paristoja", 7),
    LED_LAMPPU("LED-lamppu", 7),
    HALOGEN_LAMPPU("Halogen-lamppu", 7),
    PYYHKIJÄNSULKA("Pyyhkijänsulat", 7),
    KISSANHERKKUJA("Kissanherkkuja", 8),
    KISSANRUOKAMÄRKÄ("Kissanruokaa märkä", 8),
    KISSANRUOKAKUIVA("Kissanruokaa kuiva", 8),
    KISSANPISSAHIEKKA("Kissan pissahiekkaa", 8),
    KISSANLELU("Kissan lelu", 8),
    KISSANMINTTU("Kissanminttua", 8),
    KISSANHARJA("Kissan harja", 8),
    VESSAPAPERI("Vessapaperia", 9),
    TALOUSPAPERI("Talouspaperia", 9),
    FOLIO("Foliota", 9),
    ROSKAPUSSEJA("Roskapusseja", 9),
    ELMUKELMU("Elmukelmua", 9),
    KERTAKÄYTTÖASTIAA("Kertakäyttöastioita", 9),
    KERTAKÄYTTÖATERIN("Kertakäyttöaterimia", 9),
    KERTAKÄYTTÖLAUTANEN("Kertakäyttölautasia", 9),
    KERTAKÄYTTÖMUKI("Kertakäyttömukeja", 9),
    LEIVINPAPERI("Leivinpaperia", 9),
    SHAMPOO("Shampoota", 10),
    ISINDÖDÖ("Isin deodoranttia", 10),
    MAMINDÖDÖ("Mamin deodoranttia", 10),
    KASVOVOIDE("Kasvovoidetta", 10),
    KÄSIVOIDE("Käsivoidetta", 10),
    HUULIRASVA("Huulirasvaa", 10),
    KÄSISAIPPUA("Käsisaippuaa", 10),
    AURINKOVOIDE("Aurinkovoidetta", 10),
    HAMMASTAHNAISIMAMILLE("Hammastahnaa Isille ja Mamille", 10),
    HAMMASTAHNAMIMMILLE("Hammastahnaa Mimmille", 10),
    HAMMASHARJAISILLE("Hammasharja Isille", 10),
    HAMMASHARJAMAMILLE("Hammasharja Mamille", 10),
    HAMMASHARJAMIMMILLE("Hammasharja Mimmille", 10),
    PYYKINPESUAINE("Pyykinpesuainetta", 11),
    ASTIANPESUAINE("Astianpesuainetta", 11),
    YLEISPESUAINE("Yleispesuainetta", 11),
    LATTIANPESUAINE("Lattianpesuainetta", 11),
    PYYHE("Pyyhkeitä", 12),
    LAKANA("Lakanoita", 12),
    TYYNYLIINA("Tyynyliinoja", 12),
    PEITTO("Peittoja", 12),
    PERUNAKIINTEÄ("Perunoita kiinteä", 13),
    PERUNAJAUHO("Peruna jauhoinen", 13),
    PERUNAYLEIS("Peruna yleis", 13),
    BATAATTI("Bataattia", 13),
    PORKKANA("Porkkana", 13),
    SIPULI("Sipuli", 13),
    VALKOSIPULI("Valkosipuli", 13),
    PUNASIPULI("Punasipuli", 13),
    MAUSTEKURKKU("Maustekurkku", 13),
    RIBSIT("Ribsit", 13),
    RUOHOSIPULI("Ruohosipulia", 14),
    BASILIKATUORE("Basilikaa tuore", 14),
    VILLIRUCOLA("Villirucolaa", 14),
    TILLITUORE("Tilliä tuore", 14),
    KORIANTERITUORE("Korianteria tuore", 14),
    PERSILJATUORE("Persiljaa tuore", 14),
    OREGANOTUORE("Oreganoa tuore", 14),
    MINTTUTUORE("Minttua tuore", 14),
    TIMJAMITUORE("Timjamia tuore", 14),
    HERNEENVERSO("Herneenversoja", 15),
    THAIBASIILIKA("Thaibasilikaa", 15),
    RAKUUNATUORE("Rakuunaa tuore", 15),
    OMENA("Omenoita", 15),
    PÄÄRYNÄ("Päärynöitä", 15),
    RYPÄLE("Rypäleitä", 15),
    BANAANI("Banaaneja", 15),
    APPELSIINI("Appelsiineja", 15),
    KIWI("Kiiwejä", 15),
    LIME("Limejä", 15),
    SITRUUNA("Sitruunoita", 15),
    MANDARIINI("Mandariineja", 15),
    MANSIKKATUORE("Mansikoita tuore", 15),
    MUSTIKKATUORE("Mustikoita tuore", 15),
    VESIMELONI("Vesimelonia", 15),
    TUOREANANAS("Tuore ananas", 15),
    KURKKU("Kurkkua", 16),
    PAPRIKA("Paprikaa", 16),
    TOMAATTI("Tomaattia", 16),
    KESÄKURPITSA("Kesäkurpitsaa", 16),
    KUKKAKAALI("Kukkakaalia", 16),
    PARSAKAALI("Parsakaalia", 16),
    CHILIMEDIUM("Chili medium", 16),
    CHILIEITULINEN("Chili ei tulinen", 16),
    KIRSIKKATOMAATTI("Kirsiikkatomaatteja", 16),
    KIINANKAALI("Kiinankaalia", 16),
    KERÄKAALI("Keräkaalia", 16),
    VALKOKAALI("Valkokaalia", 16),
    KAALI("Kaalia", 16),
    SALAATTI("Salaattia", 16),
    SIPULINVARSI("Sipulinvarsia", 16),
    PURJOSIPULI("Purjosipulia", 16),
    PAKSOI("Paksoita", 16),
    INKIVÄÄRI("Inkivääriä tuore", 16),
    KEVÄTSIPULI("Kevätsipulia", 16),
    VAALEAALEIPÄ("Vaaleaa leipää", 17),
    RUISLEIPÄ("Ruisleipää", 17),
    KOKOJYVÄLEIPÄ("Kokojyväleipää", 17),
    PATONKI("Patonkia", 17),
    SAARISTOLAISLEIPÄ("Saaristolaisleipää", 17),
    OHRARIESKA("Ohrarieskaa", 17),
    HÖNÖLEIPÄ("Hönöleipää", 17),
    KAURATYYNY("Kauratyynyjä", 17),
    LEIPÄMIMMILLE("Leipää Mimmille", 17),
    LEIPÄ("Leipää", 17),
    NAUDAHJAUHELIHA("Naudan jauhelihaa", 18),
    SIKANAUTAJAUHELIHA("Sikanauta jauhelihaa", 18),
    NAUDANPAISTI("Naudanpaistia", 18),
    NAUDANPAISTISUIKALE("Naudanpaistisuikaleita", 18),
    NAUDANMINUUTTISUIKALE("Naudan minuuttisuikaleita", 18),
    PORSAANPAISTI("Porsaanpaistia", 18),
    PORSAANSISÄFILEE("Porsaan sisäfilee", 18),
    KANASUIKALE("Kanasuikaleita", 18),
    HUNAJAKANASUIKALE("Hunajamarinoituja kanasuikaleita", 18),
    KANANKOIPI("Kanankoipia", 18),
    KANANRINTAPALA("Kananrintapaloja (maustamaton)", 18),
    KANANLEIKE("Kananleikettä (maustamaton)", 18),
    HUNAJAKANANRINTAPALA("Hunajamarinoituja kananrintapaloja", 18),
    UUNILOHI("Uunilohta", 18),
    SAVULOHI("Savulohta", 18),
    KYLMÄSAVULOHI("Kylmäsavulohta", 18),
    LÄMMINSAVULOHI("Lämminsavulohta", 18),
    MAITO("Maitoa", 19),
    KERMA("Kermaa", 19),
    KUOHUKERMA("Kuohukermaa", 19),
    RUOKAKERMA("Ruokakermaa", 19),
    SMETANA("Smetanaa", 19),
    KERMAVIILI("Kermaviiliä", 19),
    RANSKANKERMA("Ranskankermaa", 19),
    TURKKILAISTAJOUGURTTI("Turkkilaista jogurttia", 19),
    HERKKUKINKKU("Herkkukinkkua", 20),
    KORPPUKINKKU("Korppukinkkua", 20),
    KALKKUNALEIKE("Kalkkunaleikettä", 20),
    MAKKARA("Makkaraa", 21),
    NAKKI("Nakkeja", 21),
    PEKONI("Pekonia", 21),
    LIHAPIIRAKKA("Lihapiirakkaa", 21),
    LIHAPULLA("Lihapullia", 21),
    VOI("Voita", 22),
    VOIMARIINI("Voimariinia", 22),
    JUUSTORAASTE("Juustoraastetta", 23),
    CHEDDAR("Cheddaria", 23),
    JUUSTO("Juustoa", 23),
    MOZZARELLA("Mozzarellaa", 23),
    PARMAGGIOREGGIANO("Parmaggiano Reggianoa", 23),
    PARMAGGIOREGGIANOLASTU("Parmaggiano Reggianoa lastuja", 23),
    FETAKUUTIO("Fetakuutioita", 23),
    FETA("Fetaa", 23),
    VALIOKOSKENLASKIJA("Valio Koskenlaskija Ruoka & Dippiä chili", 23),
    KOSKENLASKIJA("Koskenlaskijaa", 23),
    SULATEJUUSTOA("Sulatejuustoa", 23),
    KANANMUNA("Kananmuna", 24),
    ISINJUGU("Isin jugurttia", 25),
    MIMMINJUGU("Mimmin jugurttia", 25),
    PASTAKASTIKE("Pastakastiketta (Dolmio)", 26),
    PASTAKASTIKEARRABIATA("Pastakastiketta (Arrabiata)", 26),
    PASTAKASTIKEBASILIKA("Pastakastiketta (Basilika)", 26),
    MUMMONMUUSI("Mummon muusia", 26),
    SUSHINORIMERILEVÄ("Sushi nori merilevää", 26),
    PASTA("Pastaa", 27),
    RIISIÄ("Riisiä", 27),
    BASAMATIRIISI("Basmatiriisiä", 27),
    JASMINRIISI("Jasminriisiä", 27),
    RISOTTORIISI("Risottoriisiä", 27),
    TUMMARIISI("Tummaa riisiä", 27),
    MUNANUUDELI("Munanuudeleita", 27),
    NUUDELI("Nuudeleita", 27),
    SIMPUKKAPASTA("Simpukkapastaa", 27),
    KIERREPASTA("Kierrepastaa", 27),
    LASAGNE("Lasagnelevyjä", 27),
    FUSILLI("Fusillia", 27),
    TAGGLIATELLE("Taggliatellea", 27),
    SPAGETTI("Spagettia", 27),
    RAKETTISPAGETTI("Rakettispagettia", 27),
    MUROT("Muroja", 28),
    SATEENKAARIMURO("Sateenkaari muroja", 28),
    KAURAPUURO("Kaurapuuroa", 28),
    TORTILLA("Tortilloja", 28),
    TACO("Tacoja", 28),
    NACHO("Nachoja", 28),
    TACOMAUSTE("Tacomaustetta", 28),
    GUACAMOLE("Guacamolea", 28),
    SALSA("Salsaa", 28),
    JUUSTOKASTIKE("TexMex Juustokastiketta", 28),
    AURINKOKUIVATTUTOMAATTI("Aurinkokuivattuja tomaatteja", 28),
    TOMAATTIPYREE("Tomaattipyreetä", 28),
    TOMAATTIMURSKA("Tomaattimurskaa", 28),
    KOOKOSMAITO("Kookosmaitoa", 28),
    SUOLA("Suolaa", 29),
    SOKERI("Sokeria", 29),
    VEHNÄJAUHO("Vehnäjauhoja", 29),
    FARIINISOKERI("Fariinisokeria", 29),
    RUOKOSOKERI("Ruokosokeria", 29),
    HUNAJA("Hunajaa", 29),
    SIIRAPPI("Siirappia", 29),
    SOIJAKASTIKE("Soijakastiketta", 30),
    PESTOVIHREÄ("Pestoa vihreä", 30),
    SINAPPI("Sinappia", 30),
    KETSUPPI("Ketsuppia", 30),
    BBQKASTIKE("BBQ-kastiketta", 30),
    SRIRACHA("Srirachaa", 30),
    KALAKASTIKE("Kalakastiketta", 30),
    MAJONEESI("Majoneesia", 30),
    VALKOVIINIETIKKA("Valkoviinietikkaa", 30),
    RIISIVIINIETIKKA("Riisiviinietikkaa", 30),
    WORCHESTERINKASTIKE("Worchesterinkastiketta", 30),
    OLIIVIÖLJY("Oliiviöljyä", 30),
    SEESAMIÖLJY("Seesamiöljy", 30),
    RUOKAOLJY("Ruokaöljyä", 30),
    KURKKUSALAATTI("Kurkkusalaattia", 30),
    KASVISFONDI("Kasvisfondia", 30),
    KANAFONDI("Kanafondia", 30),
    NAUDANFONDI("Naudanfondia", 30),
    KASVISLIEMIKUUTIO("Kasvisliemikuutio", 30),
    NAUDANLIEMIKUUTIO("Naudanliemikuutio", 30),
    KANALIEMIKUUTIO("Kanaliemikuutio", 30),
    CURRYTAHNAPUNAINEN("Currytahnaa punainen", 30),
    OREGANO("Oreganoa", 31),
    BASILIKA("Basilikaa", 31),
    CURRY("Currya", 31),
    PAPRIKAMAUSTE("Paprikamaustetta", 31),
    KANELI("Kanelia", 31),
    KANELITANKO("Kanelitankoja", 31),
    TÄHTIANIS("Tähtianista", 31),
    RAKUUNA("Rakuunaa", 31),
    KOKONAINENNEILIKKA("Kokonaisia neilikoita (mauste)", 31),
    KADREMUMMA("Kardemummaa", 31),
    INKIVÄÄRIJAUHE("Inkiväärijauhetta", 31),
    MUSTAPIPPURI("Mustapippuria (rouhittu)", 31),
    MUSTAPIPPURIJAUHETTU("Mustapippuria (jauhettu)", 31),
    MUSTAPIPPURIKOKO("Mustapippuria kokonaisena", 31),
    MAUSTEPIPPURIKOKO("Maustepippuria kokonaisena", 31),
    MAUSTEPIPPURIJAUHETTU("Maustepippuria (jauhettu)", 31),
    VALKOPIPPURIJAUHETTU("Valkopippuria (jauhettu)", 31),
    KORIANTERINSIEMEN("Korianterinsiemeniä", 31),
    CHILIJAUHE("Chilijauhe", 31),
    ANANASPALA("Ananaspaloja", 32),
    TONNIKALA("Tonnikalaa öljyssä", 32),
    HEDELMÄSÄILYKE("Hedelmäsäilykkeitä", 32),
    HERNEKEITTO("Hernekeittoa", 32),
    KAHVI("Kahvia", 33),
    TEEISIMAMI("Teetä Isille ja Mamille", 33),
    TEEMIMMI("Teetä Mimmille", 33),
    KAAKAO("Kaakaota", 33),
    LIMSA("Limsaa", 34),
    VESI("Vettä", 34),
    MEHU("Mehua", 34),
    ANANASMEHU("Ananasmehua", 34),
    TRIP("Trip-mehua", 34),
    VIINI("Viiniä", 34),
    KALJA("Kaljaa", 34),
    SIIDERI("Siideriä", 34),
    OMENASIIDERI("Omenasiideriä", 34),
    LONKEROA("Lonkeroa", 34),
    VIINIGLÖGI("Viiniglögiä", 34),
    ENERGIAJUOMA("Energiajuomaa", 34),
    KARKKI("Karkkia", 35),
    SUKLAA("Suklaata", 35),
    TIKKARI("Tikkareita", 35),
    HAKKARA("Hakkaroita", 35),
    IRTTARI("Irttareita", 35),
    SKITTLES("Skittleseitä", 35),
    SIPSI("Sipsejä", 36),
    POPCORN("Popcornia", 36),
    SUOLATIKKU("Suolatikkuja", 36),
    PÄHKINÄ("Pähkinöitä", 37),
    MAAPÄHKINÄ("Maapähkinöitä", 37),
    PÄHKINÄSEKOITUS("Pähkinäsekoitus", 37),
    PINJANSIEMEN("Pinjansiemeniä", 37),
    URHEILUJUOMA("Urheilujuomaa", 37),
    PROTEIINIPATUKKA("Proteiinipatukkaa", 37),
    PROTEIINIJUOMA("Proteiinijuomaa", 37),
    URHEILUTABLETTI("Urheilutabletti", 37),
    PAKASTEMANSIKKA("Pakastemansikkaa", 37),
    PAKASTEMARJA("Pakastemarjoja", 37),
    JÄÄTELÖPAKETTI("Jäätelöpaketti", 38),
    JÄÄTELÖPUIKKO("Jäätelöpuikko", 38),
    SEITI("Seitiä", 39),
    PIZZAISI("Pizzaa isille", 40),
    PIZZAMAMI("Pizzaa mamille", 40),
    PERUNASIPULI("Peruna-Sipulisekoitus", 41),
    KASVISSUIKALE("Kasvissuikaleita", 41),
    SUIKALEJUURES("Suikalejuurekset", 41),
    WOKVIHANNES("Wokvihanneksia", 41),
    AURINKOKASVIS("Aurinkokasviksia", 41),
    HERNEMAISSIPAPRIKA("Hernemaissipaprikaa", 41),
    KEITTOJUURES("Keittojuureksia", 41),
    SIPULIKUUTIO("Sipulikuutioita", 41),
    PAPUVIHREÄ("Papuja vihreitä (pakaste)", 41),
    PAKASTEPATONKI("Pakastepatonkia", 41),
    THAICUBE("Thaicubeja", 41),
    KANANUGETTIPAKASTE("Kananugetteja pakaste", 41),
    KALAPUIKKOJA("Kalapuikkoja", 41),
    SYNTTÄRIKORTTI("Synttärikortti", 42),
    LAHJAPUSSI("Lahjapussi", 42),
    LAHJAPAPERI("Lahjapaperi", 42),
    MULTA("Multaa", 42),
    KUKKA("Kukkia", 42);

    private final String tuote;
    private final int osastoId;


    Tuotteet(String tuote, int osastoId) {
        this.tuote = tuote;
        this.osastoId = osastoId;
    }

    public String getTuote() {
        return tuote;
    }

    public int getOsastoId() {
        return osastoId;
    }



    @Override
    public String toString() {
        return "Tuote: " + tuote + ", Osasto: " + osastoId;
    }
}
