package fi.ruoka.ostoslista.enums;

public enum Tuotteet {
    LENKKARIT("Lenkkarit", 1, Yksikko.KAPPALE.getYksikko()),
    LUISTIMET("Luistimet", 1, Yksikko.KAPPALE.getYksikko()),
    JÄÄKIEKKOTEIPPI("Kiekkoteippi", 1, Yksikko.KAPPALE.getYksikko()),
    JÄÄKIEKKOKYPÄRÄ("Jääkiekkokypärä", 1, Yksikko.KAPPALE.getYksikko()),
    PYÖRÄILYKYPÄRÄ("Pyöräilykypärä", 1, Yksikko.KAPPALE.getYksikko()),
    JALKAPALLO("Jalkapallo", 1, Yksikko.KAPPALE.getYksikko()),
    PYÖRÄNLUKKO("Pyöränlukko", 1, Yksikko.KAPPALE.getYksikko()),
    POLKUPYÖRÄ("Polkupyörä", 1, Yksikko.KAPPALE.getYksikko()),
    LATURI("Laturi", 2, Yksikko.KAPPALE.getYksikko()),
    NÄYTÖNSUOJA("Näytönsuoja", 2, Yksikko.KAPPALE.getYksikko()),
    HAMMASHARJANVAIHTOPÄÄ("Hammasharjan vaihtopää", 2, Yksikko.PAKETTI.getYksikko()),
    SÄHKÖHAMMASHARJA("Sähköhammasharja", 2, Yksikko.KAPPALE.getYksikko()),
    KENGÄTMIMMI("Kengät Mimmille", 3, Yksikko.PARI.getYksikko()),
    KENGÄTISI("Kengät Isille", 3, Yksikko.PARI.getYksikko()),
    TOSSUMIMMI("Sisätossut Mimmille", 3, Yksikko.PARI.getYksikko()),
    SLÄPÄRITISI("Släpärit Isille", 3, Yksikko.PARI.getYksikko()),
    SLÄPÄRITMIMMI("Släpärit Mimmille", 3, Yksikko.PARI.getYksikko()),
    BOKSERITISI("Bokserit Isille", 4, Yksikko.PAKETTI.getYksikko()),
    PIKKARITMIMMI("Pikkarit Mimmille", 4, Yksikko.PAKETTI.getYksikko()),
    URHEILUSUKATISI("Urheilusukat Isille", 4, Yksikko.PAKETTI.getYksikko()),
    SUKATISI("Sukat Isille", 4, Yksikko.PAKETTI.getYksikko()),
    SUKATMIMMI("Sukat Mimmille", 4, Yksikko.PAKETTI.getYksikko()),
    SUKATÄITI("Sukat Äidille", 4, Yksikko.PAKETTI.getYksikko()),
    LIPPISMIMMI("Lippis Mimmille", 4, Yksikko.KAPPALE.getYksikko()),
    PIIRUSTUSPAPERIA("Piirustuspaperia", 5, Yksikko.PAKETTI.getYksikko()),
    KYNÄ("Kyniä", 5, Yksikko.PAKETTI.getYksikko()),
    KUULAKÄRKIKYNÄ("Kuulakärkikyniä", 5, Yksikko.PAKETTI.getYksikko()),
    LYIJYKYNÄ("Lyijykyniä", 5, Yksikko.PAKETTI.getYksikko()),
    TUSSI("Tusseja", 5, Yksikko.PAKETTI.getYksikko()),
    VÄRIKYNÄ("Värikyniä", 5, Yksikko.PAKETTI.getYksikko()),
    VÄRITYSKIRJA("Värityskirja", 5, Yksikko.KAPPALE.getYksikko()),
    KIRJA("Kirja", 5, Yksikko.KAPPALE.getYksikko()),
    ASKARTELUKIRJA("Askartelukirja", 5, Yksikko.KAPPALE.getYksikko()),
    PALAPELI("Palapeli", 6, Yksikko.KAPPALE.getYksikko()),
    NUKKE("Nukke", 6, Yksikko.KAPPALE.getYksikko()),
    AUTO("Auto", 6, Yksikko.KAPPALE.getYksikko()),
    PALIKAT("Palikat", 6, Yksikko.PAKETTI.getYksikko()),
    LELUMIMMI("Lelu Mimmille", 6, Yksikko.KAPPALE.getYksikko()),
    LELULAHJAKSI("Lelu Lahjaksi", 6, Yksikko.KAPPALE.getYksikko()),
    POKEMONKORTTI("Pokemonkortteja", 6, Yksikko.PAKETTI.getYksikko()),
    AA_PARISTO("AA-paristoja", 7, Yksikko.PAKETTI.getYksikko()),
    AAA_PARISTO("AAA-paristoja", 7, Yksikko.PAKETTI.getYksikko()),
    LR_44_PARISTO("LR44-paristoja", 7, Yksikko.PAKETTI.getYksikko()),
    CR2032_PARISTO("CR2032-paristoja", 7, Yksikko.PAKETTI.getYksikko()),
    LED_LAMPPU("LED-lamppu", 7, Yksikko.KAPPALE.getYksikko()),
    HALOGEN_LAMPPU("Halogen-lamppu", 7, Yksikko.KAPPALE.getYksikko()),
    PYYHKIJÄNSULKA("Pyyhkijänsulat", 7, Yksikko.PAKETTI.getYksikko()),
    KISSANHERKKUJA("Kissanherkkuja", 8, Yksikko.PUSSI.getYksikko()),
    KISSANRUOKAMÄRKÄ("Kissanruokaa märkä", 8, Yksikko.PAKETTI.getYksikko()),
    KISSANRUOKAKUIVA("Kissanruokaa kuiva", 8, Yksikko.PUSSI.getYksikko()),
    KISSANPISSAHIEKKA("Kissan pissahiekkaa", 8, Yksikko.PUSSI.getYksikko()),
    KISSANLELU("Kissan lelu", 8, Yksikko.KAPPALE.getYksikko()),
    KISSANMINTTU("Kissanminttua", 8, Yksikko.PUSSI.getYksikko()),
    KISSANHARJA("Kissan harja", 8, Yksikko.KAPPALE.getYksikko()),
    VESSAPAPERI("Vessapaperia", 9, Yksikko.PAKETTI.getYksikko()),
    TALOUSPAPERI("Talouspaperia", 9, Yksikko.PAKETTI.getYksikko()),
    FOLIO("Foliota", 9, Yksikko.RULLA.getYksikko()),
    ROSKAPUSSEJA("Roskapusseja", 9, Yksikko.RULLA.getYksikko()),
    ELMUKELMU("Elmukelmua", 9, Yksikko.RULLA.getYksikko()),
    KERTAKÄYTTÖASTIAA("Kertakäyttöastioita", 9, Yksikko.PAKETTI.getYksikko()),
    KERTAKÄYTTÖATERIN("Kertakäyttöaterimia", 9, Yksikko.PAKETTI.getYksikko()),
    KERTAKÄYTTÖLAUTANEN("Kertakäyttölautasia", 9, Yksikko.PAKETTI.getYksikko()),
    KERTAKÄYTTÖMUKI("Kertakäyttömukeja", 9, Yksikko.PAKETTI.getYksikko()),
    LEIVINPAPERI("Leivinpaperia", 9, Yksikko.RULLA.getYksikko()),
    SHAMPOO("Shampoota", 10, Yksikko.PULLO.getYksikko()),
    ISINDÖDÖ("Isin deodoranttia", 10, Yksikko.KAPPALE.getYksikko()),
    MAMINDÖDÖ("Mamin deodoranttia", 10, Yksikko.KAPPALE.getYksikko()),
    KASVOVOIDE("Kasvovoidetta", 10, Yksikko.PURKKI.getYksikko()),
    KÄSIVOIDE("Käsivoidetta", 10, Yksikko.PURKKI.getYksikko()),
    HUULIRASVA("Huulirasvaa", 10, Yksikko.KAPPALE.getYksikko()),
    KÄSISAIPPUA("Käsisaippuaa", 10, Yksikko.PULLO.getYksikko()),
    AURINKOVOIDE("Aurinkovoidetta", 10, Yksikko.PURKKI.getYksikko()),
    HAMMASTAHNAISIMAMILLE("Hammastahnaa Isille ja Mamille", 10, Yksikko.TUUBI.getYksikko()),
    HAMMASTAHNAMIMMILLE("Hammastahnaa Mimmille", 10, Yksikko.TUUBI.getYksikko()),
    HAMMASHARJAISILLE("Hammasharja Isille", 10, Yksikko.KAPPALE.getYksikko()),
    HAMMASHARJAMAMILLE("Hammasharja Mamille", 10, Yksikko.KAPPALE.getYksikko()),
    HAMMASHARJAMIMMILLE("Hammasharja Mimmille", 10, Yksikko.KAPPALE.getYksikko()),
    PYYKINPESUAINE("Pyykinpesuainetta", 11, Yksikko.PULLO.getYksikko()),
    ASTIANPESUAINE("Astianpesuainetta", 11, Yksikko.PUSSI.getYksikko()),
    YLEISPESUAINE("Yleispesuainetta", 11, Yksikko.PULLO.getYksikko()),
    LATTIANPESUAINE("Lattianpesuainetta", 11, Yksikko.PULLO.getYksikko()),
    PYYHE("Pyyhkeitä", 12, Yksikko.KAPPALE.getYksikko()),
    LAKANA("Lakanoita", 12, Yksikko.KAPPALE.getYksikko()),
    TYYNYLIINA("Tyynyliinoja", 12, Yksikko.KAPPALE.getYksikko()),
    PEITTO("Peittoja", 12, Yksikko.KAPPALE.getYksikko()),
    PERUNAKIINTEÄ("Perunoita kiinteä", 13, Yksikko.KILOGRAMMA.getYksikko()),
    PERUNAJAUHO("Peruna jauhoinen", 13, Yksikko.KILOGRAMMA.getYksikko()),
    PERUNAYLEIS("Peruna yleis", 13, Yksikko.KILOGRAMMA.getYksikko()),
    BATAATTI("Bataattia", 13, Yksikko.KILOGRAMMA.getYksikko()),
    PORKKANA("Porkkana", 13, Yksikko.PUSSI.getYksikko()),
    SIPULI("Sipuli", 13, Yksikko.PUSSI.getYksikko()),
    VALKOSIPULI("Valkosipuli", 13, Yksikko.PUSSI.getYksikko()),
    PUNASIPULI("Punasipuli", 13, Yksikko.PUSSI.getYksikko()),
    MAUSTEKURKKU("Maustekurkku", 13, Yksikko.KAPPALE.getYksikko()),
    RIBSIT("Ribsit", 13, Yksikko.KILOGRAMMA.getYksikko()),
    RUOHOSIPULI("Ruohosipulia", 14, Yksikko.RUUKKU.getYksikko()),
    BASILIKATUORE("Basilikaa tuore", 14, Yksikko.RUUKKU.getYksikko()),
    VILLIRUCOLA("Villirucolaa", 14, Yksikko.RUUKKU.getYksikko()),
    TILLITUORE("Tilliä tuore", 14, Yksikko.RUUKKU.getYksikko()),
    KORIANTERITUORE("Korianteria tuore", 14, Yksikko.RUUKKU.getYksikko()),
    PERSILJATUORE("Persiljaa tuore", 14, Yksikko.RUUKKU.getYksikko()),
    OREGANOTUORE("Oreganoa tuore", 14, Yksikko.RUUKKU.getYksikko()),
    MINTTUTUORE("Minttua tuore", 14, Yksikko.RUUKKU.getYksikko()),
    TIMJAMITUORE("Timjamia tuore", 14, Yksikko.RUUKKU.getYksikko()),
    HERNEENVERSO("Herneenversoja", 15, Yksikko.RUUKKU.getYksikko()),
    THAIBASIILIKA("Thaibasilikaa", 15, Yksikko.RUUKKU.getYksikko()),
    RAKUUNATUORE("Rakuunaa tuore", 15, Yksikko.RUUKKU.getYksikko()),
    OMENA("Omenoita", 15, Yksikko.KAPPALE.getYksikko()),
    PÄÄRYNÄ("Päärynöitä", 15, Yksikko.KAPPALE.getYksikko()),
    RYPÄLE("Rypäleitä", 15, Yksikko.RASIA.getYksikko()),
    BANAANI("Banaaneja", 15, Yksikko.KAPPALE.getYksikko()),
    APPELSIINI("Appelsiineja", 15, Yksikko.KAPPALE.getYksikko()),
    KIWI("Kiiwejä", 15, Yksikko.KAPPALE.getYksikko()),
    LIME("Limejä", 15, Yksikko.KAPPALE.getYksikko()),
    SITRUUNA("Sitruunoita", 15, Yksikko.KAPPALE.getYksikko()),
    MANDARIINI("Mandariineja", 15, Yksikko.PUSSI.getYksikko()),
    MANSIKKATUORE("Mansikoita tuore", 15, Yksikko.RASIA.getYksikko()),
    MUSTIKKATUORE("Mustikoita tuore", 15, Yksikko.RASIA.getYksikko()),
    VESIMELONI("Vesimelonia", 15, Yksikko.KAPPALE.getYksikko()),
    TUOREANANAS("Tuore ananas", 15, Yksikko.KAPPALE.getYksikko()),
    KURKKU("Kurkkua", 16, Yksikko.KAPPALE.getYksikko()),
    PAPRIKA("Paprikaa", 16, Yksikko.KAPPALE.getYksikko()),
    TOMAATTI("Tomaattia", 16, Yksikko.KAPPALE.getYksikko()),
    KESÄKURPITSA("Kesäkurpitsaa", 16, Yksikko.KAPPALE.getYksikko()),
    KUKKAKAALI("Kukkakaalia", 16, Yksikko.KAPPALE.getYksikko()),
    PARSAKAALI("Parsakaalia", 16, Yksikko.KAPPALE.getYksikko()),
    CHILIMEDIUM("Chili medium", 16, Yksikko.KAPPALE.getYksikko()),
    CHILIEITULINEN("Chili ei tulinen", 16, Yksikko.KAPPALE.getYksikko()),
    KIRSIKKATOMAATTI("Kirsikkatomaatteja", 16, Yksikko.RASIA.getYksikko()),
    KIINANKAALI("Kiinankaalia", 16, Yksikko.KAPPALE.getYksikko()),
    KERÄKAALI("Keräkaalia", 16, Yksikko.KAPPALE.getYksikko()),
    VALKOKAALI("Valkokaalia", 16, Yksikko.KAPPALE.getYksikko()),
    KAALI("Kaalia", 16, Yksikko.KAPPALE.getYksikko()),
    SALAATTI("Salaattia", 16, Yksikko.KAPPALE.getYksikko()),
    SIPULINVARSI("Sipulinvarsia", 16, Yksikko.PUSSI.getYksikko()),
    PURJOSIPULI("Purjosipulia", 16, Yksikko.KAPPALE.getYksikko()),
    PAKSOI("Paksoita", 16, Yksikko.KAPPALE.getYksikko()),
    INKIVÄÄRI("Inkivääriä tuore", 16, Yksikko.KAPPALE.getYksikko()),
    KEVÄTSIPULI("Kevätsipulia", 16, Yksikko.PUSSI.getYksikko()),
    VAALEAALEIPÄ("Vaaleaa leipää", 17, Yksikko.KAPPALE.getYksikko()),
    PAAHTOLEIPÄ("Paahtoleipää", 17, Yksikko.KAPPALE.getYksikko()),
    RUISLEIPÄ("Ruisleipää", 17, Yksikko.KAPPALE.getYksikko()),
    KOKOJYVÄLEIPÄ("Kokojyväleipää", 17, Yksikko.KAPPALE.getYksikko()),
    PATONKI("Patonkia", 17, Yksikko.KAPPALE.getYksikko()),
    SAARISTOLAISLEIPÄ("Saaristolaisleipää", 17, Yksikko.KAPPALE.getYksikko()),
    OHRARIESKA("Ohrarieskaa", 17, Yksikko.KAPPALE.getYksikko()),
    HÖNÖLEIPÄ("Hönöleipää", 17, Yksikko.KAPPALE.getYksikko()),
    KAURATYYNY("Kauratyynyjä", 17, Yksikko.KAPPALE.getYksikko()),
    LEIPÄMIMMILLE("Leipää Mimmille", 17, Yksikko.KAPPALE.getYksikko()),
    LEIPÄ("Leipää", 17, Yksikko.KAPPALE.getYksikko()),
    NAUDAHJAUHELIHA("Naudan jauhelihaa", 18, Yksikko.GRAMMA.getYksikko()),
    SIKANAUTAJAUHELIHA("Sikanauta jauhelihaa", 18, Yksikko.GRAMMA.getYksikko()),
    NAUDANPAISTI("Naudanpaistia", 18, Yksikko.GRAMMA.getYksikko()),
    NAUDANPAISTISUIKALE("Naudanpaistisuikaleita", 18, Yksikko.GRAMMA.getYksikko()),
    NAUDANMINUUTTISUIKALE("Naudan minuuttisuikaleita", 18, Yksikko.GRAMMA.getYksikko()),
    PORSAANPAISTI("Porsaanpaistia", 18, Yksikko.GRAMMA.getYksikko()),
    PORSAANSISÄFILEE("Porsaan sisäfilee", 18, Yksikko.GRAMMA.getYksikko()),
    KANASUIKALE("Kanasuikaleita", 18, Yksikko.GRAMMA.getYksikko()),
    HUNAJAKANASUIKALE("Hunajamarinoituja kanasuikaleita", 18, Yksikko.GRAMMA.getYksikko()),
    KANANKOIPI("Kanankoipia", 18, Yksikko.RASIA.getYksikko()),
    KANANRINTAPALA("Kananrintapaloja (maustamaton)", 18, Yksikko.GRAMMA.getYksikko()),
    KANANLEIKE("Kananleikettä (maustamaton)", 18, Yksikko.GRAMMA.getYksikko()),
    HUNAJAKANANRINTAPALA("Hunajamarinoituja kananrintapaloja", 18, Yksikko.GRAMMA.getYksikko()),
    UUNILOHI("Uunilohta", 18, Yksikko.GRAMMA.getYksikko()),
    SAVULOHI("Savulohta", 18, Yksikko.GRAMMA.getYksikko()),
    KYLMÄSAVULOHI("Kylmäsavulohta", 18, Yksikko.GRAMMA.getYksikko()),
    LÄMMINSAVULOHI("Lämminsavulohta", 18, Yksikko.GRAMMA.getYksikko()),
    MAITO("Maitoa", 19, Yksikko.TÖLKKI.getYksikko()),
    KERMA("Kermaa", 19, Yksikko.DESILITRA.getYksikko()),
    KUOHUKERMA("Kuohukermaa", 19, Yksikko.DESILITRA.getYksikko()),
    RUOKAKERMA("Ruokakermaa", 19, Yksikko.DESILITRA.getYksikko()),
    SMETANA("Smetanaa", 19, Yksikko.PURKKI.getYksikko()),
    KERMAVIILI("Kermaviiliä", 19, Yksikko.PURKKI.getYksikko()),
    RANSKANKERMA("Ranskankermaa", 19, Yksikko.PURKKI.getYksikko()),
    TURKKILAISTAJOGURTTI("Turkkilaista jogurttia", 19, Yksikko.PURKKI.getYksikko()),
    HERKKUKINKKU("Herkkukinkkua", 20, Yksikko.PAKETTI.getYksikko()),
    KORPPUKINKKU("Korppukinkkua", 20, Yksikko.PAKETTI.getYksikko()),
    KALKKUNALEIKE("Kalkkunaleikettä", 20, Yksikko.PAKETTI.getYksikko()),
    MAKKARA("Makkaraa", 21, Yksikko.PAKETTI.getYksikko()),
    NAKKI("Nakkeja", 21, Yksikko.PAKETTI.getYksikko()),
    PEKONI("Pekonia", 21, Yksikko.PAKETTI.getYksikko()),
    LIHAPIIRAKKA("Lihapiirakkaa", 21, Yksikko.PUSSI.getYksikko()),
    KINKKUSUIKALE("Kinkkusuikaleita", 21, Yksikko.PUSSI.getYksikko()),
    LIHAPULLA("Lihapullia", 21, Yksikko.PAKETTI.getYksikko()),
    VOI("Voita", 22, Yksikko.PAKETTI.getYksikko()),
    VOIMARIINI("Voimariinia", 22, Yksikko.RASIA.getYksikko()),
    JUUSTORAASTE("Juustoraastetta", 23, Yksikko.PUSSI.getYksikko()),
    CHEDDAR("Cheddaria", 23, Yksikko.PAKETTI.getYksikko()),
    JUUSTO("Juustoa", 23, Yksikko.PAKETTI.getYksikko()),
    MOZZARELLA("Mozzarellaa", 23, Yksikko.PUSSI.getYksikko()),
    PARMAGGIOREGGIANO("Parmaggiano Reggianoa", 23, Yksikko.PUSSI.getYksikko()),
    PARMAGGIOREGGIANOLASTU("Parmaggiano Reggianoa lastuja", 23, Yksikko.RASIA.getYksikko()),
    FETAKUUTIO("Fetakuutioita", 23, Yksikko.RASIA.getYksikko()),
    FETA("Fetaa", 23, Yksikko.PAKETTI.getYksikko()),
    VALIOKOSKENLASKIJA("Valio Koskenlaskija Ruoka & Dippiä chili", 23, Yksikko.PAKETTI.getYksikko()),
    KOSKENLASKIJA("Koskenlaskijaa", 23, Yksikko.PAKETTI.getYksikko()),
    SULATEJUUSTOA("Sulatejuustoa", 23, Yksikko.PURKKI.getYksikko()),
    KANANMUNA("Kananmuna", 24, Yksikko.KAPPALE.getYksikko()),
    KANANMUNAKENNO("Kananmunakenno", 24, Yksikko.KAPPALE.getYksikko()),
    ISINJUGU("Isin jugurttia", 25, Yksikko.PURKKI.getYksikko()),
    MIMMINJUGU("Mimmin jugurttia", 25, Yksikko.PURKKI.getYksikko()),
    PASTAKASTIKE("Pastakastiketta (Dolmio)", 26, Yksikko.PURKKI.getYksikko()),
    PASTAKASTIKEARRABIATA("Pastakastiketta (Arrabiata)", 26, Yksikko.PURKKI.getYksikko()),
    PASTAKASTIKEBASILIKA("Pastakastiketta (Basilika)", 26, Yksikko.PURKKI.getYksikko()),
    PIERUPASTAA("Pierupastaa/Italian pataa", 26, Yksikko.PUSSI.getYksikko()),
    MUMMONMUUSI("Mummon muusia", 26, Yksikko.PAKETTI.getYksikko()),
    SUSHINORIMERILEVÄ("Sushi nori merilevää", 26, Yksikko.PAKETTI.getYksikko()),
    PASTA("Pastaa", 27, Yksikko.PUSSI.getYksikko()),
    RYHMAHAUPASTA("Ryhmä Hau Pastaa", 27, Yksikko.PUSSI.getYksikko()),
    PIPSAPOSSUPASTA("Pipsa Possu Pastaa", 27, Yksikko.PUSSI.getYksikko()),
    RIISIÄ("Riisiä", 27, Yksikko.PAKETTI.getYksikko()),
    BASAMATIRIISI("Basmatiriisiä", 27, Yksikko.PAKETTI.getYksikko()),
    JASMINRIISI("Jasminriisiä", 27, Yksikko.PAKETTI.getYksikko()),
    RISOTTORIISI("Risottoriisiä", 27, Yksikko.PAKETTI.getYksikko()),
    TUMMARIISI("Tummaa riisiä", 27, Yksikko.PAKETTI.getYksikko()),
    MUNANUUDELI("Munanuudeleita", 27, Yksikko.PAKETTI.getYksikko()),
    NUUDELI("Nuudeleita", 27, Yksikko.PAKETTI.getYksikko()),
    SIMPUKKAPASTA("Simpukkapastaa", 27, Yksikko.PUSSI.getYksikko()),
    KIERREPASTA("Kierrepastaa", 27, Yksikko.PUSSI.getYksikko()),
    LASAGNE("Lasagnelevyjä", 27, Yksikko.PAKETTI.getYksikko()),
    FUSILLI("Fusillia", 27, Yksikko.PUSSI.getYksikko()),
    TAGGLIATELLE("Taggliatellea", 27, Yksikko.PUSSI.getYksikko()),
    SPAGETTI("Spagettia", 27, Yksikko.PUSSI.getYksikko()),
    RAKETTISPAGETTI("Rakettispagettia", 27, Yksikko.PUSSI.getYksikko()),
    MUROT("Muroja", 28, Yksikko.PAKETTI.getYksikko()),
    SATEENKAARIMURO("Sateenkaari muroja", 28, Yksikko.PAKETTI.getYksikko()),
    KAURAPUURO("Kaurapuuroa", 28, Yksikko.PAKETTI.getYksikko()),
    TORTILLA("Tortilloja", 28, Yksikko.PAKETTI.getYksikko()),
    TACO("Tacoja", 28, Yksikko.PAKETTI.getYksikko()),
    NACHO("Nachoja", 28, Yksikko.PUSSI.getYksikko()),
    TACOMAUSTE("Tacomaustetta", 28, Yksikko.PUSSI.getYksikko()),
    GUACAMOLE("Guacamolea", 28, Yksikko.PURKKI.getYksikko()),
    SALSA("Salsaa", 28, Yksikko.PURKKI.getYksikko()),
    JUUSTOKASTIKE("TexMex Juustokastiketta", 28, Yksikko.PURKKI.getYksikko()),
    AURINKOKUIVATTUTOMAATTI("Aurinkokuivattuja tomaatteja", 28, Yksikko.PURKKI.getYksikko()),
    TOMAATTIPYREE("Tomaattipyreetä", 28, Yksikko.PURKKI.getYksikko()),
    TOMAATTIMURSKA("Tomaattimurskaa", 28, Yksikko.PURKKI.getYksikko()),
    KOOKOSMAITO("Kookosmaitoa", 28, Yksikko.PURKKI.getYksikko()),
    SUOLA("Suolaa", 29, Yksikko.PAKETTI.getYksikko()),
    SOKERI("Sokeria", 29, Yksikko.PUSSI.getYksikko()),
    PALASOKERI("Palasokeria", 29, Yksikko.PAKETTI.getYksikko()),
    VEHNÄJAUHO("Vehnäjauhoja", 29, Yksikko.PUSSI.getYksikko()),
    FARIINISOKERI("Fariinisokeria", 29, Yksikko.PUSSI.getYksikko()),
    RUOKOSOKERI("Ruokosokeria", 29, Yksikko.PUSSI.getYksikko()),
    HUNAJA("Hunajaa", 29, Yksikko.PURKKI.getYksikko()),
    SIIRAPPI("Siirappia", 29, Yksikko.PURKKI.getYksikko()),
    TUMMASIIRAPPI("Tummaa siirappia", 29, Yksikko.PURKKI.getYksikko()),
    SOIJAKASTIKE("Soijakastiketta", 30, Yksikko.PULLO.getYksikko()),
    PESTOVIHREÄ("Pestoa vihreä", 30, Yksikko.PURKKI.getYksikko()),
    SINAPPI("Sinappia", 30, Yksikko.TUUBI.getYksikko()),
    KETSUPPI("Ketsuppia", 30, Yksikko.PURKKI.getYksikko()),
    BBQKASTIKE("BBQ-kastiketta", 30, Yksikko.PURKKI.getYksikko()),
    CHILIKASTIKE("Chilikastiketta", 30, Yksikko.PULLO.getYksikko()),
    SRIRACHA("Srirachaa", 30, Yksikko.PURKKI.getYksikko()),
    KALAKASTIKE("Kalakastiketta", 30, Yksikko.PULLO.getYksikko()),
    MAJONEESI("Majoneesia", 30, Yksikko.PURKKI.getYksikko()),
    VALKOVIINIETIKKA("Valkoviinietikkaa", 30, Yksikko.PULLO.getYksikko()),
    RIISIVIINIETIKKA("Riisiviinietikkaa", 30, Yksikko.PULLO.getYksikko()),
    WORCHESTERINKASTIKE("Worchesterinkastiketta", 30, Yksikko.PULLO.getYksikko()),
    OLIIVIÖLJY("Oliiviöljyä", 30, Yksikko.PULLO.getYksikko()),
    SEESAMIÖLJY("Seesamiöljy", 30, Yksikko.PULLO.getYksikko()),
    RUOKAOLJY("Ruokaöljyä", 30, Yksikko.PULLO.getYksikko()),
    KURKKUSALAATTI("Kurkkusalaattia", 30, Yksikko.PURKKI.getYksikko()),
    KASVISFONDI("Kasvisfondia", 30, Yksikko.PAKETTI.getYksikko()),
    KANAFONDI("Kanafondia", 30, Yksikko.PAKETTI.getYksikko()),
    NAUDANFONDI("Naudanfondia", 30, Yksikko.PAKETTI.getYksikko()),
    KASVISLIEMIKUUTIO("Kasvisliemikuutio", 30, Yksikko.PAKETTI.getYksikko()),
    NAUDANLIEMIKUUTIO("Naudanliemikuutio", 30, Yksikko.PAKETTI.getYksikko()),
    KANALIEMIKUUTIO("Kanaliemikuutio", 30, Yksikko.PAKETTI.getYksikko()),
    CURRYTAHNAPUNAINEN("Currytahnaa punainen", 30, Yksikko.PURKKI.getYksikko()),
    CURRYTAHNA("Currytahnaa", 30, Yksikko.PURKKI.getYksikko()),
    OREGANO("Oreganoa", 31, Yksikko.PUSSI.getYksikko()),
    BASILIKA("Basilikaa", 31, Yksikko.PUSSI.getYksikko()),
    CURRY("Currya", 31, Yksikko.PUSSI.getYksikko()),
    PAPRIKAMAUSTE("Paprikajauhetta", 31, Yksikko.PUSSI.getYksikko()),
    KANELI("Kanelia", 31, Yksikko.PUSSI.getYksikko()),
    KANELITANKO("Kanelitankoja", 31, Yksikko.PUSSI.getYksikko()),
    TÄHTIANIS("Tähtianista", 31, Yksikko.PUSSI.getYksikko()),
    RAKUUNA("Rakuunaa", 31, Yksikko.PUSSI.getYksikko()),
    KOKONAINENNEILIKKA("Kokonaisia neilikoita (mauste)", 31, Yksikko.PUSSI.getYksikko()),
    KADREMUMMA("Kardemummaa", 31, Yksikko.PUSSI.getYksikko()),
    INKIVÄÄRIJAUHE("Inkiväärijauhetta", 31, Yksikko.PUSSI.getYksikko()),
    MUSTAPIPPURI("Mustapippuria (rouhittu)", 31, Yksikko.PUSSI.getYksikko()),
    MUSTAPIPPURIJAUHETTU("Mustapippuria (jauhettu)", 31, Yksikko.PUSSI.getYksikko()),
    MUSTAPIPPURIKOKO("Mustapippuria kokonaisena", 31, Yksikko.PUSSI.getYksikko()),
    MAUSTEPIPPURIKOKO("Maustepippuria kokonaisena", 31, Yksikko.PUSSI.getYksikko()),
    MAUSTEPIPPURIJAUHETTU("Maustepippuria (jauhettu)", 31, Yksikko.PUSSI.getYksikko()),
    VALKOPIPPURIJAUHETTU("Valkopippuria (jauhettu)", 31, Yksikko.PUSSI.getYksikko()),
    KORIANTERINSIEMEN("Korianterinsiemeniä", 31, Yksikko.PUSSI.getYksikko()),
    CHILIJAUHE("Chilijauhe", 31, Yksikko.PUSSI.getYksikko()),
    ANANASPALA("Ananaspaloja", 32, Yksikko.PURKKI.getYksikko()),
    TONNIKALA("Tonnikalaa öljyssä", 32, Yksikko.PURKKI.getYksikko()),
    HEDELMÄSÄILYKE("Hedelmäsäilykkeitä", 32, Yksikko.PURKKI.getYksikko()),
    HERNEKEITTO("Hernekeittoa", 32, Yksikko.PURKKI.getYksikko()),
    KAHVI("Kahvia", 33, Yksikko.PAKETTI.getYksikko()),
    KAHVINSUODATIN("Kahvinsuodattimia", 33, Yksikko.PAKETTI.getYksikko()),
    TEEISIMAMI("Teetä Isille ja Mamille", 33, Yksikko.PAKETTI.getYksikko()),
    TEEMIMMI("Teetä Mimmille", 33, Yksikko.PAKETTI.getYksikko()),
    KAAKAO("Kaakaota", 33, Yksikko.PAKETTI.getYksikko()),
    LIMSA("Limsaa", 34, Yksikko.PULLO.getYksikko()),
    VESI("Vettä", 34, Yksikko.PULLO.getYksikko()),
    MEHU("Mehua", 34, Yksikko.TÖLKKI.getYksikko()),
    ANANASMEHU("Ananasmehua", 34, Yksikko.TÖLKKI.getYksikko()),
    TRIP("Trip-mehua", 34, Yksikko.PURKKI.getYksikko()),
    MEHUTIIVISTE("Mehutiivistettä", 34, Yksikko.PULLO.getYksikko()),
    KALJA("Kaljaa", 34, Yksikko.TÖLKKI.getYksikko()),
    SIIDERI("Siideriä", 34, Yksikko.TÖLKKI.getYksikko()),
    OMENASIIDERI("Omenasiideriä", 34, Yksikko.TÖLKKI.getYksikko()),
    LONKEROA("Lonkeroa", 34, Yksikko.TÖLKKI.getYksikko()),
    VIINIGLÖGI("Viiniglögiä", 34, Yksikko.PULLO.getYksikko()),
    ENERGIAJUOMA("Energiajuomaa", 34, Yksikko.TÖLKKI.getYksikko()),
    KARKKI("Karkkia", 35, Yksikko.PUSSI.getYksikko()),
    SUKLAA("Suklaata", 35, Yksikko.KAPPALE.getYksikko()),
    TIKKARI("Tikkareita", 35, Yksikko.KAPPALE.getYksikko()),
    HAKKARA("Hakkaroita", 35, Yksikko.PUSSI.getYksikko()),
    IRTTARI("Irttareita", 35, Yksikko.PUSSI.getYksikko()),
    SKITTLES("Skittleseitä", 35, Yksikko.PUSSI.getYksikko()),
    SIPSI("Sipsejä", 36, Yksikko.PUSSI.getYksikko()),
    POPCORN("Popcornia", 36, Yksikko.PUSSI.getYksikko()),
    SUOLATIKKU("Suolatikkuja", 36, Yksikko.PUSSI.getYksikko()),
    PÄHKINÄ("Pähkinöitä", 37, Yksikko.PUSSI.getYksikko()),
    MAAPÄHKINÄ("Maapähkinöitä", 37, Yksikko.PUSSI.getYksikko()),
    PÄHKINÄSEKOITUS("Pähkinäsekoitus", 37, Yksikko.PUSSI.getYksikko()),
    PINJANSIEMEN("Pinjansiemeniä", 37, Yksikko.PUSSI.getYksikko()),
    URHEILUJUOMA("Urheilujuomaa", 37, Yksikko.PULLO.getYksikko()),
    PROTEIINIPATUKKA("Proteiinipatukkaa", 37, Yksikko.KAPPALE.getYksikko()),
    PROTEIINIJUOMA("Proteiinijuomaa", 37, Yksikko.PULLO.getYksikko()),
    URHEILUTABLETTI("Urheilutabletti", 37, Yksikko.PURKKI.getYksikko()),
    PAKASTEMANSIKKA("Pakastemansikkaa", 37, Yksikko.PUSSI.getYksikko()),
    PAKASTEMARJA("Pakastemarjoja", 37, Yksikko.PUSSI.getYksikko()),
    PAKASTEMUSTIKKA("Pakastemustikkaa", 37, Yksikko.PUSSI.getYksikko()),
    JÄÄTELÖPAKETTI("Jäätelöpaketti", 38, Yksikko.PAKETTI.getYksikko()),
    JÄÄTELÖPUIKKO("Jäätelöpuikko", 38, Yksikko.KAPPALE.getYksikko()),
    SEITI("Seitiä", 39, Yksikko.PAKETTI.getYksikko()),
    PIZZAISI("Pizzaa isille", 40, Yksikko.KAPPALE.getYksikko()),
    PIZZAMAMI("Pizzaa mamille", 40, Yksikko.KAPPALE.getYksikko()),
    PERUNASIPULI("Peruna-Sipulisekoitus", 41, Yksikko.PUSSI.getYksikko()),
    ISOPERUNASIPULI("Iso Peruna-Sipulisekoitus", 41, Yksikko.PUSSI.getYksikko()),
    KASVISSUIKALE("Kasvissuikaleita", 41, Yksikko.PUSSI.getYksikko()),
    SUIKALEJUURES("Suikalejuurekset", 41, Yksikko.PUSSI.getYksikko()),
    WOKVIHANNES("Wokvihanneksia", 41, Yksikko.PUSSI.getYksikko()),
    AURINKOKASVIS("Aurinkokasviksia", 41, Yksikko.PUSSI.getYksikko()),
    HERNEMAISSIPAPRIKA("Hernemaissipaprikaa", 41, Yksikko.PUSSI.getYksikko()),
    KEITTOJUURES("Keittojuureksia", 41, Yksikko.PUSSI.getYksikko()),
    SIPULIKUUTIO("Sipulikuutioita", 41, Yksikko.PUSSI.getYksikko()),
    PAPUVIHREÄ("Papuja vihreitä (pakaste)", 41, Yksikko.PUSSI.getYksikko()),
    RANSKANPERUNA("Ranskanperunoita", 41, Yksikko.PUSSI.getYksikko()),
    PAKASTEPATONKI("Pakastepatonkia", 41, Yksikko.PUSSI.getYksikko()),
    THAICUBE("Thaicubeja", 41, Yksikko.PAKETTI.getYksikko()),
    KANANUGETTIPAKASTE("Kananugetteja pakaste", 41, Yksikko.PAKETTI.getYksikko()),
    KALAPUIKKOJA("Kalapuikkoja", 41, Yksikko.PAKETTI.getYksikko()),
    SYNTTÄRIKORTTI("Synttärikortti", 42, Yksikko.KAPPALE.getYksikko()),
    LAHJAPUSSI("Lahjapussi", 42, Yksikko.KAPPALE.getYksikko()),
    LAHJAPAPERI("Lahjapaperi", 42, Yksikko.KAPPALE.getYksikko()),
    MULTA("Multaa", 43, Yksikko.PUSSI.getYksikko()),
    KUKKA("Kukkia", 43, Yksikko.KAPPALE.getYksikko()),
    VIINI("Viiniä", 44, Yksikko.PULLO.getYksikko()),
    NIKOTIINIPUSSIT("Nikotiinipusseja", 44, Yksikko.PURKKI.getYksikko()),
    TUPAKKA("Tupakkaa", 44, Yksikko.PAKETTI.getYksikko()),;

    private final String tuote;
    private final int osastoId;
    private final String yksikkoOstoslistassa;

    Tuotteet(String tuote, int osastoId, String yksikkoOstoslistassa) {
        this.tuote = tuote;
        this.osastoId = osastoId;
        this.yksikkoOstoslistassa = yksikkoOstoslistassa;
    }

    public String getTuote() {
        return tuote;
    }

    public int getOsastoId() {
        return osastoId;
    }

    public String getYksikkoOstoslistassa() {
        return yksikkoOstoslistassa;
    }

    @Override
    public String toString() {
        return "Tuote: " + tuote + ", Osasto: " + osastoId + ", Yksikkö ostoslistassa: " + yksikkoOstoslistassa;
    }
}
