name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #     with:
  #       install: true
        
  #   - name: login to docker hub
  #     id: docker-hub
  #     env:
  #       username: ${{secrets.DOCKERHUB_USERNAME}}
  #       password: ${{secrets.DOCKERHUB_PASSWORD}}
  #     run: |
  #       docker login -u $username -p $password 
  #   - name: Build and Push Docker Image
  #     env:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     run: |
  #       docker buildx build --platform linux/arm64 \
  #         -t $username/ostoslista-app:latest \
  #         --push .

  vpn_and_ssh_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

          echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
          chmod 600 vpn-config.ovpn

      - name: Setup VPN Connection
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: vpn-config.ovpn
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}

      - name: SSH into Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'Connected via VPN!'"
