name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
        
    - name: login to docker hub
      id: docker-hub
      env:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        docker login -u $username -p $password 
    - name: Build and Push Docker Image
      env:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        docker buildx build --platform linux/arm64 \
          -t $username/ostoslista-app:latest \
          --push .
    #- name: Build the Docker image
    #  run : docker build --platform linux/arm64 . --file Dockerfile --tag ${{secrets.DOCKERHUB_USERNAME}}/ostoslista-app:latest
    #- name: push the docker image
    #  id: push-docker-image
    #  run: docker push ${{secrets.DOCKERHUB_USERNAME}}/ostoslista-app:latest
