name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2

  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #     with:
  #       install: true
        
  #   - name: login to docker hub
  #     id: docker-hub
  #     env:
  #       username: ${{secrets.DOCKERHUB_USERNAME}}
  #       password: ${{secrets.DOCKERHUB_PASSWORD}}
  #     run: |
  #       docker login -u $username -p $password 
  #   - name: Build and Push Docker Image
  #     env:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     run: |
  #       docker buildx build --platform linux/arm64 \
  #         -t $username/ostoslista-app:latest \
  #         --push .

  vpn_and_ssh_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install OpenVPN
        run: sudo apt-get update && sudo apt-get install -y openvpn

      - name: Setup VPN Connection
        env:
          VPN_USERNAME: ${{ secrets.VPN_USERNAME }}
          VPN_PASSWORD: ${{ secrets.VPN_PASSWORD }}
        run: |
          # Save the VPN config file if it's provided as a secret
          echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
          cat vpn-config.ovpn
          
          # Use OpenVPN with the configuration and credentials
          sudo openvpn --config vpn-config.ovpn --auth-user-pass <(echo -e "$VPN_USERNAME\n$VPN_PASSWORD") &
          sleep 10 # Allow some time to establish the VPN connection

      - name: SSH into Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -o StrictHostKeyChecking=no username@server_ip "echo 'Connected via VPN!'"
